"""Registry for grounded synthetic classifier capabilities (8 pilot languages)."""
from __future__ import annotations

LANG_NAMES = {
    "en": "English", "de": "German", "fr": "French", "es": "Spanish",
    "it": "Italian", "pt": "Portuguese", "nl": "Dutch", "pl": "Polish",
    "tr": "Turkish", "ja": "Japanese", "zh": "Chinese", "hi": "Hindi", "ru": "Russian",
}
PILOT_LANGS = ("en", "de", "fr", "es", "it", "pt", "nl", "pl")
# Languages of held-out gate cells without a seed corpus of their own: the writer gets an English
# passage and writes in the target language (round3).
EXTRA_LANGS = ("tr", "ja", "zh", "hi", "ru")

# Canonical English labels (target index order).
URGENCY_LABELS = ("not urgent", "soon", "critical")
NLI_LABELS = ("entailment", "contradiction", "neutral")
SPAM_LABELS = ("spam", "not spam")
SARCASM_LABELS = ("sarcastic", "sincere")
EMOTION_LABELS = ("anger", "fear", "joy", "sadness", "surprise", "disgust", "neutral")
CLAIM_LABELS = ("checkable claim", "opinion", "no claim")
STANCE_LABELS = ("favour", "against", "neutral")
READING_LABELS = ("yes", "no", "not answerable")
# ClaimBuster taxonomy, the wording of the fact_check training rows and the held-out suite.
FACTCHECK_LABELS = ("check worthy", "unimportant factual", "non factual")
SENTIMENT_LABELS = ("negative", "neutral", "positive")
INJECTION_LABELS = ("injection", "benign")
# Yes/no tasks in the noul format of the gate suites: the first label is "yes" (target index 1).
PII_LABELS = ("contains pii", "no pii")
FORMALITY_LABELS = ("formal", "informal")

_SYSTEM = (
    "Create grounded classifier data from the supplied source passage. Use only its topic and facts. "
    "Do not copy a sentence of eight or more words. Return one JSON object and no commentary."
)
_VERIFY_SYSTEM = (
    "Independently label the classifier item from its text. You are not shown another model's label. "
    "Return one JSON object and no explanation."
)

_URGENCY_LOCAL = {
    "en": {"question": "How urgent is this request?",
           "local_labels": ("not urgent", "soon", "critical")},
    "de": {"question": "Wie dringend ist diese Anfrage?",
           "local_labels": ("nicht dringend", "bald", "kritisch")},
    "fr": {"question": "Quel est le degré d’urgence de cette demande ?",
           "local_labels": ("pas urgent", "bientôt", "critique")},
    "es": {"question": "¿Qué grado de urgencia tiene esta solicitud?",
           "local_labels": ("no urgente", "pronto", "crítico")},
    "it": {"question": "Quanto è urgente questa richiesta?",
           "local_labels": ("non urgente", "presto", "critico")},
    "pt": {"question": "Qual é a urgência deste pedido?",
           "local_labels": ("não urgente", "breve", "crítico")},
    "nl": {"question": "Hoe dringend is dit verzoek?",
           "local_labels": ("niet dringend", "binnenkort", "kritiek")},
    "pl": {"question": "Jak pilna jest ta prośba?",
           "local_labels": ("niepilne", "wkrótce", "krytyczne")},
}
_NLI_LOCAL = {
    "en": {"question": "How are the premise and hypothesis related?",
           "pair_fields": ("Premise", "Hypothesis"),
           "criteria": ("follows from the premise", "conflicts with the premise",
                        "is neither supported nor contradicted"),
           "local_labels": ("entailment", "contradiction", "neutral")},
    "de": {"question": "Wie hängen Prämisse und Hypothese zusammen?",
           "pair_fields": ("Prämisse", "Hypothese"),
           "criteria": ("folgt aus der Prämisse", "widerspricht der Prämisse",
                        "wird weder gestützt noch widerlegt"),
           "local_labels": ("folgerung", "widerspruch", "neutral")},
    "fr": {"question": "Quel est le lien entre la prémisse et l’hypothèse ?",
           "pair_fields": ("Prémisse", "Hypothèse"),
           "criteria": ("découle de la prémisse", "contredit la prémisse",
                        "n’est ni étayée ni contredite"),
           "local_labels": ("implication", "contradiction", "neutre")},
    "es": {"question": "¿Qué relación hay entre la premisa y la hipótesis?",
           "pair_fields": ("Premisa", "Hipótesis"),
           "criteria": ("se deduce de la premisa", "contradice la premisa",
                        "no está respaldada ni contradicha"),
           "local_labels": ("implicación", "contradicción", "neutral")},
    "it": {"question": "Qual è il rapporto tra premessa e ipotesi?",
           "pair_fields": ("Premessa", "Ipotesi"),
           "criteria": ("deriva dalla premessa", "contraddice la premessa",
                        "non è né sostenuta né contraddetta"),
           "local_labels": ("implicazione", "contraddizione", "neutrale")},
    "pt": {"question": "Qual é a relação entre a premissa e a hipótese?",
           "pair_fields": ("Premissa", "Hipótese"),
           "criteria": ("decorre da premissa", "contradiz a premissa",
                        "não é apoiada nem contradita"),
           "local_labels": ("implicação", "contradição", "neutro")},
    "nl": {"question": "Wat is het verband tussen de premisse en de hypothese?",
           "pair_fields": ("Premisse", "Hypothese"),
           "criteria": ("volgt uit de premisse", "spreekt de premisse tegen",
                        "wordt niet ondersteund of tegengesproken"),
           "local_labels": ("gevolgtrekking", "tegenspraak", "neutraal")},
    "pl": {"question": "Jaki jest związek między przesłanką a hipotezą?",
           "pair_fields": ("Przesłanka", "Hipoteza"),
           "criteria": ("wynika z przesłanki", "jest sprzeczna z przesłanką",
                        "nie jest ani potwierdzona, ani obalona"),
           "local_labels": ("wynikanie", "sprzeczność", "neutralne")},
}
_SPAM_LOCAL = {
    "en": {"question": "Is this message spam?",
           "criteria": ("unsolicited advertising, phishing, scam or deceptive bulk message",
                        "a genuine personal or business message"),
           "local_labels": ("spam", "not spam")},
    "de": {"question": "Ist diese Nachricht Spam?",
           "criteria": ("unerwünschte Werbung, Phishing, Betrug oder irreführende Massennachricht",
                        "eine echte private oder geschäftliche Nachricht"),
           "local_labels": ("spam", "kein spam")},
    "fr": {"question": "Ce message est-il du spam ?",
           "criteria": ("publicité non sollicitée, hameçonnage, arnaque ou envoi massif trompeur",
                        "un message personnel ou professionnel authentique"),
           "local_labels": ("spam", "pas spam")},
    "es": {"question": "¿Es spam este mensaje?",
           "criteria": ("publicidad no solicitada, phishing, estafa o mensaje masivo engañoso",
                        "un mensaje personal o comercial genuino"),
           "local_labels": ("spam", "no es spam")},
    "it": {"question": "Questo messaggio è spam?",
           "criteria": ("pubblicità non richiesta, phishing, truffa o messaggio massivo ingannevole",
                        "un messaggio personale o aziendale autentico"),
           "local_labels": ("spam", "non spam")},
    "pt": {"question": "Esta mensagem é spam?",
           "criteria": ("publicidade não solicitada, phishing, fraude ou mensagem em massa enganosa",
                        "uma mensagem pessoal ou comercial genuína"),
           "local_labels": ("spam", "não é spam")},
    "nl": {"question": "Is dit bericht spam?",
           "criteria": ("ongewenste reclame, phishing, oplichting of misleidend bulkbericht",
                        "een echt persoonlijk of zakelijk bericht"),
           "local_labels": ("spam", "geen spam")},
    "pl": {"question": "Czy ta wiadomość to spam?",
           "criteria": ("niechciana reklama, phishing, oszustwo lub masowa wiadomość wprowadzająca w błąd",
                        "prawdziwa wiadomość osobista lub służbowa"),
           "local_labels": ("spam", "nie spam")},
}
_SARCASM_LOCAL = {
    "en": {"question": "Is this comment sarcastic?",
           "criteria": ("meant ironically, opposite of the literal wording",
                        "meant sincerely, matching the literal wording"),
           "local_labels": ("sarcastic", "sincere")},
    "de": {"question": "Ist dieser Kommentar sarkastisch?",
           "criteria": ("ironisch gemeint, Gegenteil des wörtlichen Sinns",
                        "aufrichtig gemeint, entspricht dem wörtlichen Sinn"),
           "local_labels": ("sarkastisch", "aufrichtig")},
    "fr": {"question": "Ce commentaire est-il sarcastique ?",
           "criteria": ("dit avec ironie, contraire du sens littéral",
                        "dit sincèrement, conforme au sens littéral"),
           "local_labels": ("sarcastique", "sincère")},
    "es": {"question": "¿Es sarcástico este comentario?",
           "criteria": ("dicho con ironía, opuesto al sentido literal",
                        "dicho en serio, acorde al sentido literal"),
           "local_labels": ("sarcástico", "sincero")},
    "it": {"question": "Questo commento è sarcastico?",
           "criteria": ("detto con ironia, opposto al senso letterale",
                        "detto sul serio, coerente con il senso letterale"),
           "local_labels": ("sarcastico", "sincero")},
    "pt": {"question": "Este comentário é sarcástico?",
           "criteria": ("dito com ironia, oposto ao sentido literal",
                        "dito a sério, alinhado ao sentido literal"),
           "local_labels": ("sarcástico", "sincero")},
    "nl": {"question": "Is deze opmerking sarcastisch?",
           "criteria": ("ironisch bedoeld, tegenovergestelde van de letterlijke betekenis",
                        "oprecht bedoeld, in lijn met de letterlijke betekenis"),
           "local_labels": ("sarcastisch", "oprecht")},
    "pl": {"question": "Czy ten komentarz jest sarkastyczny?",
           "criteria": ("powiedziany z ironią, przeciwieństwo dosłownego sensu",
                        "powiedziany szczerze, zgodnie z dosłownym sensem"),
           "local_labels": ("sarkastyczny", "szczery")},
}
_EMOTION_LOCAL = {
    "en": {"question": "What emotion does this statement express?",
           "criteria": ("anger", "fear", "joy", "sadness", "surprise", "disgust", "no strong emotion"),
           "local_labels": ("anger", "fear", "joy", "sadness", "surprise", "disgust", "neutral")},
    "de": {"question": "Welche Emotion drückt diese Aussage aus?",
           "criteria": ("Ärger", "Angst", "Freude", "Traurigkeit", "Überraschung", "Ekel", "keine starke Emotion"),
           "local_labels": ("ärger", "angst", "freude", "traurigkeit", "überraschung", "ekel", "neutral")},
    "fr": {"question": "Quelle émotion exprime cette déclaration ?",
           "criteria": ("colère", "peur", "joie", "tristesse", "surprise", "dégoût", "pas d’émotion forte"),
           "local_labels": ("colère", "peur", "joie", "tristesse", "surprise", "dégoût", "neutre")},
    "es": {"question": "¿Qué emoción expresa esta declaración?",
           "criteria": ("ira", "miedo", "alegría", "tristeza", "sorpresa", "asco", "sin emoción fuerte"),
           "local_labels": ("ira", "miedo", "alegría", "tristeza", "sorpresa", "asco", "neutral")},
    "it": {"question": "Quale emozione esprime questa dichiarazione?",
           "criteria": ("rabbia", "paura", "gioia", "tristezza", "sorpresa", "disgusto", "nessuna emozione forte"),
           "local_labels": ("rabbia", "paura", "gioia", "tristezza", "sorpresa", "disgusto", "neutrale")},
    "pt": {"question": "Que emoção esta declaração expressa?",
           "criteria": ("raiva", "medo", "alegria", "tristeza", "surpresa", "nojo", "sem emoção forte"),
           "local_labels": ("raiva", "medo", "alegria", "tristeza", "surpresa", "nojo", "neutro")},
    "nl": {"question": "Welke emotie drukt deze uitspraak uit?",
           "criteria": ("woede", "angst", "vreugde", "verdriet", "verbazing", "walging", "geen sterke emotie"),
           "local_labels": ("woede", "angst", "vreugde", "verdriet", "verbazing", "walging", "neutraal")},
    "pl": {"question": "Jaką emocję wyraża to stwierdzenie?",
           "criteria": ("złość", "strach", "radość", "smutek", "zaskoczenie", "obrzydzenie", "brak silnej emocji"),
           "local_labels": ("złość", "strach", "radość", "smutek", "zaskoczenie", "obrzydzenie", "neutralne")},
    "tr": {"question": "Bu ifade hangi duyguyu yansıtıyor?",
           "criteria": ("öfke", "korku", "sevinç", "üzüntü", "şaşkınlık", "tiksinti", "güçlü bir duygu yok"),
           "local_labels": ("öfke", "korku", "sevinç", "üzüntü", "şaşkınlık", "tiksinti", "nötr")},
    "ja": {"question": "この発言はどの感情を表していますか？",
           "criteria": ("怒り", "恐れ", "喜び", "悲しみ", "驚き", "嫌悪", "強い感情はない"),
           "local_labels": ("怒り", "恐れ", "喜び", "悲しみ", "驚き", "嫌悪", "中立")},
    "zh": {"question": "这段话表达了什么情绪？",
           "criteria": ("愤怒", "恐惧", "喜悦", "悲伤", "惊讶", "厌恶", "没有强烈情绪"),
           "local_labels": ("愤怒", "恐惧", "喜悦", "悲伤", "惊讶", "厌恶", "中性")},
    "hi": {"question": "यह कथन कौन-सी भावना व्यक्त करता है?",
           "criteria": ("गुस्सा", "डर", "खुशी", "उदासी", "आश्चर्य", "घृणा", "कोई तीव्र भावना नहीं"),
           "local_labels": ("गुस्सा", "डर", "खुशी", "उदासी", "आश्चर्य", "घृणा", "तटस्थ")},
    "ru": {"question": "Какую эмоцию выражает это высказывание?",
           "criteria": ("гнев", "страх", "радость", "грусть", "удивление", "отвращение", "нет сильной эмоции"),
           "local_labels": ("гнев", "страх", "радость", "грусть", "удивление", "отвращение", "нейтрально")},
}
_CLAIM_LOCAL = {
    "en": {"question": "What kind of statement is this?",
           "criteria": ("a factual statement that could be verified",
                        "a value judgement or preference",
                        "a question, request or small talk"),
           "local_labels": ("checkable claim", "opinion", "no claim")},
    "de": {"question": "Um welche Art Aussage handelt es sich?",
           "criteria": ("eine überprüfbare Tatsachenbehauptung",
                        "ein Werturteil oder eine Präferenz",
                        "eine Frage, Bitte oder Smalltalk"),
           "local_labels": ("prüfbare behauptung", "meinung", "keine behauptung")},
    "fr": {"question": "Quel type d’énoncé est-ce ?",
           "criteria": ("un fait vérifiable",
                        "un jugement de valeur ou une préférence",
                        "une question, une demande ou une formule de politesse"),
           "local_labels": ("affirmation vérifiable", "opinion", "pas d’affirmation")},
    "es": {"question": "¿Qué tipo de enunciado es?",
           "criteria": ("una afirmación factual comprobable",
                        "un juicio de valor o preferencia",
                        "una pregunta, petición o charla informal"),
           "local_labels": ("afirmación comprobable", "opinión", "sin afirmación")},
    "it": {"question": "Che tipo di affermazione è?",
           "criteria": ("un’affermazione fattuale verificabile",
                        "un giudizio di valore o una preferenza",
                        "una domanda, richiesta o convenevole"),
           "local_labels": ("affermazione verificabile", "opinione", "nessuna affermazione")},
    "pt": {"question": "Que tipo de afirmação é esta?",
           "criteria": ("uma afirmação factual verificável",
                        "um juízo de valor ou preferência",
                        "uma pergunta, pedido ou conversa casual"),
           "local_labels": ("afirmação verificável", "opinião", "sem afirmação")},
    "nl": {"question": "Wat voor uitspraak is dit?",
           "criteria": ("een verifieerbare feitelijke bewering",
                        "een waardeoordeel of voorkeur",
                        "een vraag, verzoek of smalltalk"),
           "local_labels": ("verifieerbare bewering", "mening", "geen bewering")},
    "pl": {"question": "Jaki to rodzaj wypowiedzi?",
           "criteria": ("weryfikowalne stwierdzenie faktograficzne",
                        "osąd wartościowy lub preferencja",
                        "pytanie, prośba lub pogawędka"),
           "local_labels": ("weryfikowalne twierdzenie", "opinia", "brak twierdzenia")},
}
_STANCE_LOCAL = {
    "en": {"question": "What is this comment’s stance toward the measure in the passage?",
           "pair_fields": ("Passage", "Comment"),
           "criteria": ("supports the measure", "opposes the measure", "neither supports nor opposes clearly"),
           "local_labels": ("favour", "against", "neutral")},
    "de": {"question": "Welche Haltung nimmt dieser Kommentar zur Maßnahme in der Passage ein?",
           "pair_fields": ("Passage", "Kommentar"),
           "criteria": ("unterstützt die Maßnahme", "lehnt die Maßnahme ab", "weder klar dafür noch dagegen"),
           "local_labels": ("befürwortet die maßnahme", "lehnt die maßnahme ab", "neutral")},
    "fr": {"question": "Quelle position ce commentaire prend-il sur la mesure du texte ?",
           "pair_fields": ("Texte", "Commentaire"),
           "criteria": ("favorable à la mesure", "contre la mesure", "ni pour ni contre clairement"),
           "local_labels": ("pour", "contre", "neutre")},
    "es": {"question": "¿Qué postura tiene este comentario sobre la medida del texto?",
           "pair_fields": ("Texto", "Comentario"),
           "criteria": ("a favor de la medida", "en contra de la medida", "ni a favor ni en contra con claridad"),
           "local_labels": ("a favor", "en contra", "neutral")},
    "it": {"question": "Che posizione esprime questo commento sulla misura nel testo?",
           "pair_fields": ("Testo", "Commento"),
           "criteria": ("a favore della misura", "contro la misura", "né a favore né contro in modo chiaro"),
           "local_labels": ("a favore", "contro", "neutrale")},
    "pt": {"question": "Qual é a posição deste comentário sobre a medida no texto?",
           "pair_fields": ("Texto", "Comentário"),
           "criteria": ("a favor da medida", "contra a medida", "nem a favor nem contra com clareza"),
           "local_labels": ("favorável à medida", "contrário à medida", "neutro")},
    "nl": {"question": "Wat is het standpunt van deze opmerking over de maatregel in de tekst?",
           "pair_fields": ("Tekst", "Opmerking"),
           "criteria": ("voor de maatregel", "tegen de maatregel", "noch duidelijk voor noch tegen"),
           "local_labels": ("voor de maatregel", "tegen de maatregel", "neutraal standpunt")},
    "pl": {"question": "Jakie jest stanowisko tego komentarza wobec środka w tekście?",
           "pair_fields": ("Tekst", "Komentarz"),
           "criteria": ("za środkiem", "przeciw środku", "ani wyraźnie za, ani przeciw"),
           "local_labels": ("za", "przeciw", "neutralne")},
}
_READING_LOCAL = {
    "en": {"question": "How does the passage answer this question?",
           "pair_fields": ("Passage", "Question"),
           "criteria": ("yes, the passage confirms it",
                        "no, the passage rules it out",
                        "the passage does not say"),
           "local_labels": ("yes", "no", "not answerable")},
    "de": {"question": "Wie beantwortet die Passage diese Frage?",
           "pair_fields": ("Passage", "Frage"),
           "criteria": ("ja, die Passage bestätigt es",
                        "nein, die Passage schließt es aus",
                        "die Passage sagt dazu nichts"),
           "local_labels": ("ja", "nein", "nicht beantwortbar")},
    "fr": {"question": "Comment le texte répond-il à cette question ?",
           "pair_fields": ("Texte", "Question"),
           "criteria": ("oui, le texte le confirme",
                        "non, le texte l’exclut",
                        "le texte ne le dit pas"),
           "local_labels": ("oui", "non", "sans réponse")},
    "es": {"question": "¿Cómo responde el texto a esta pregunta?",
           "pair_fields": ("Texto", "Pregunta"),
           "criteria": ("sí, el texto lo confirma",
                        "no, el texto lo descarta",
                        "el texto no lo dice"),
           "local_labels": ("sí", "no", "sin respuesta")},
    "it": {"question": "Come risponde il testo a questa domanda?",
           "pair_fields": ("Testo", "Domanda"),
           "criteria": ("sì, il testo lo conferma",
                        "no, il testo lo esclude",
                        "il testo non lo dice"),
           "local_labels": ("sì", "no", "senza risposta")},
    "pt": {"question": "Como o texto responde a esta pergunta?",
           "pair_fields": ("Texto", "Pergunta"),
           "criteria": ("sim, o texto confirma",
                        "não, o texto exclui",
                        "o texto não o diz"),
           "local_labels": ("sim", "não", "sem resposta")},
    "nl": {"question": "Hoe beantwoordt de tekst deze vraag?",
           "pair_fields": ("Tekst", "Vraag"),
           "criteria": ("ja, de tekst bevestigt het",
                        "nee, de tekst sluit het uit",
                        "de tekst zegt het niet"),
           "local_labels": ("ja", "nee", "niet beantwoordbaar")},
    "pl": {"question": "Jak tekst odpowiada na to pytanie?",
           "pair_fields": ("Tekst", "Pytanie"),
           "criteria": ("tak, tekst to potwierdza",
                        "nie, tekst to wyklucza",
                        "tekst tego nie mówi"),
           "local_labels": ("tak", "nie", "brak odpowiedzi")},
}


_FACTCHECK_LOCAL = {
    "en": {"question": "How should this statement be judged?",
           "criteria": ("a factual claim about an important public matter that people would want verified",
                        "factual but not important to check",
                        "an opinion, promise, question or statement without a factual claim"),
           "local_labels": ("check worthy", "unimportant factual", "non factual")},
    "de": {"question": "Wie ist diese Aussage einzuordnen?",
           "criteria": ("eine Tatsachenbehauptung zu einer wichtigen öffentlichen Frage, die man überprüfen möchte",
                        "sachlich, aber nicht wichtig genug zum Prüfen",
                        "eine Meinung, ein Versprechen, eine Frage oder eine Aussage ohne Tatsachenbehauptung"),
           "local_labels": ("prüfenswert", "unwichtig sachlich", "nicht sachlich")},
    "fr": {"question": "Comment faut-il juger cette déclaration ?",
           "criteria": ("une affirmation factuelle sur une question publique importante que l’on voudrait vérifier",
                        "factuelle mais pas assez importante pour être vérifiée",
                        "une opinion, une promesse, une question ou une déclaration sans affirmation factuelle"),
           "local_labels": ("à vérifier", "factuel sans importance", "non factuel")},
    "es": {"question": "¿Cómo debe valorarse esta afirmación?",
           "criteria": ("una afirmación factual sobre un asunto público importante que conviene verificar",
                        "factual pero sin importancia para verificar",
                        "una opinión, promesa, pregunta o frase sin afirmación factual"),
           "local_labels": ("verificable importante", "factual sin importancia", "no factual")},
    "it": {"question": "Come va giudicata questa affermazione?",
           "criteria": ("un’affermazione fattuale su una questione pubblica importante da verificare",
                        "fattuale ma non abbastanza importante da verificare",
                        "un’opinione, una promessa, una domanda o una frase senza affermazione fattuale"),
           "local_labels": ("da verificare", "fattuale irrilevante", "non fattuale")},
    "pt": {"question": "Como deve ser avaliada esta afirmação?",
           "criteria": ("uma afirmação factual sobre um assunto público importante que se quer verificar",
                        "factual, mas sem importância para verificar",
                        "uma opinião, promessa, pergunta ou frase sem afirmação factual"),
           "local_labels": ("a verificar", "factual sem importância", "não factual")},
    "nl": {"question": "Hoe moet deze uitspraak worden beoordeeld?",
           "criteria": ("een feitelijke bewering over een belangrijke publieke kwestie die men wil controleren",
                        "feitelijk, maar niet belangrijk genoeg om te controleren",
                        "een mening, belofte, vraag of uitspraak zonder feitelijke bewering"),
           "local_labels": ("controlewaardig", "onbelangrijk feitelijk", "niet feitelijk")},
    "pl": {"question": "Jak należy ocenić tę wypowiedź?",
           "criteria": ("twierdzenie o faktach w ważnej sprawie publicznej, które warto sprawdzić",
                        "oparte na faktach, ale nieistotne do sprawdzenia",
                        "opinia, obietnica, pytanie lub wypowiedź bez twierdzenia o faktach"),
           "local_labels": ("warte sprawdzenia", "nieistotny fakt", "bez faktów")},
}
_SENTIMENT_LOCAL = {
    "en": {"question": "What sentiment does this text express?",
           "criteria": ("an unfavorable or displeased opinion", "no clear positive or negative opinion",
                        "a favorable or pleased opinion"),
           "local_labels": ("negative", "neutral", "positive")},
    "de": {"question": "Welche Stimmung drückt dieser Text aus?",
           "criteria": ("eine ablehnende oder unzufriedene Meinung", "keine klar positive oder negative Meinung",
                        "eine zustimmende oder zufriedene Meinung"),
           "local_labels": ("negativ", "neutral", "positiv")},
    "fr": {"question": "Quel sentiment ce texte exprime-t-il ?",
           "criteria": ("une opinion défavorable ou mécontente", "aucune opinion clairement positive ou négative",
                        "une opinion favorable ou satisfaite"),
           "local_labels": ("négatif", "neutre", "positif")},
    "es": {"question": "¿Qué sentimiento expresa este texto?",
           "criteria": ("una opinión desfavorable o insatisfecha", "ninguna opinión claramente positiva o negativa",
                        "una opinión favorable o satisfecha"),
           "local_labels": ("negativo", "neutral", "positivo")},
    "it": {"question": "Quale sentimento esprime questo testo?",
           "criteria": ("un’opinione sfavorevole o insoddisfatta", "nessuna opinione chiaramente positiva o negativa",
                        "un’opinione favorevole o soddisfatta"),
           "local_labels": ("negativo", "neutrale", "positivo")},
    "pt": {"question": "Que sentimento este texto expressa?",
           "criteria": ("uma opinião desfavorável ou insatisfeita", "nenhuma opinião claramente positiva ou negativa",
                        "uma opinião favorável ou satisfeita"),
           "local_labels": ("negativo", "neutro", "positivo")},
    "nl": {"question": "Welk sentiment drukt deze tekst uit?",
           "criteria": ("een ongunstige of ontevreden mening", "geen duidelijk positieve of negatieve mening",
                        "een gunstige of tevreden mening"),
           "local_labels": ("negatief", "neutraal", "positief")},
    "pl": {"question": "Jaki wydźwięk ma ten tekst?",
           "criteria": ("nieprzychylna lub niezadowolona opinia", "brak wyraźnie pozytywnej lub negatywnej opinii",
                        "przychylna lub zadowolona opinia"),
           "local_labels": ("negatywny", "neutralny", "pozytywny")},
    "tr": {"question": "Bu metin nasıl bir görüş bildiriyor?",
           "criteria": ("olumsuz veya memnuniyetsiz bir görüş", "açıkça olumlu ya da olumsuz bir görüş yok",
                        "olumlu veya memnun bir görüş"),
           "local_labels": ("olumsuz", "nötr", "olumlu")},
    "ja": {"question": "このテキストはどのような評価を表していますか？",
           "criteria": ("否定的または不満な意見", "はっきりした肯定・否定の意見がない", "肯定的または満足した意見"),
           "local_labels": ("否定的", "中立", "肯定的")},
    "zh": {"question": "这段文字表达了什么情感倾向？",
           "criteria": ("负面或不满的意见", "没有明显的正面或负面意见", "正面或满意的意见"),
           "local_labels": ("负面", "中性", "正面")},
    "hi": {"question": "यह पाठ किस तरह की राय व्यक्त करता है?",
           "criteria": ("नकारात्मक या असंतुष्ट राय", "कोई स्पष्ट सकारात्मक या नकारात्मक राय नहीं",
                        "सकारात्मक या संतुष्ट राय"),
           "local_labels": ("नकारात्मक", "तटस्थ", "सकारात्मक")},
    "ru": {"question": "Какую оценку выражает этот текст?",
           "criteria": ("неблагоприятное или недовольное мнение", "нет явно положительного или отрицательного мнения",
                        "благоприятное или довольное мнение"),
           "local_labels": ("отрицательная", "нейтральная", "положительная")},
}
_INJECTION_LOCAL = {
    "en": {"question": "Does this text try to give instructions to an AI system?",
           "criteria": ("it tries to override, redirect or instruct an AI assistant or agent that reads it",
                        "ordinary content with no hidden instruction aimed at an AI"),
           "local_labels": ("injection", "benign")},
    "de": {"question": "Versucht dieser Text, einem KI-System Anweisungen zu geben?",
           "criteria": ("er versucht, einen KI-Assistenten oder -Agenten, der ihn liest, umzulenken oder zu steuern",
                        "gewöhnlicher Inhalt ohne versteckte Anweisung an eine KI"),
           "local_labels": ("injektion", "harmlos")},
    "fr": {"question": "Ce texte essaie-t-il de donner des instructions à un système d’IA ?",
           "criteria": ("il tente de détourner ou de commander un assistant ou agent d’IA qui le lit",
                        "un contenu ordinaire sans instruction cachée destinée à une IA"),
           "local_labels": ("injection", "anodin")},
    "es": {"question": "¿Intenta este texto dar instrucciones a un sistema de IA?",
           "criteria": ("intenta desviar o dar órdenes a un asistente o agente de IA que lo lee",
                         "contenido normal sin instrucciones ocultas dirigidas a una IA"),
           "local_labels": ("inyección", "inofensivo")},
    "it": {"question": "Questo testo cerca di dare istruzioni a un sistema di IA?",
           "criteria": ("cerca di deviare o comandare un assistente o agente di IA che lo legge",
                        "contenuto normale senza istruzioni nascoste rivolte a un’IA"),
           "local_labels": ("iniezione", "innocuo")},
    "pt": {"question": "Este texto tenta dar instruções a um sistema de IA?",
           "criteria": ("tenta desviar ou comandar um assistente ou agente de IA que o lê",
                        "conteúdo comum sem instruções ocultas dirigidas a uma IA"),
           "local_labels": ("injeção", "inofensivo")},
    "nl": {"question": "Probeert deze tekst een AI-systeem instructies te geven?",
           "criteria": ("hij probeert een AI-assistent of -agent die hem leest om te leiden of te sturen",
                        "gewone inhoud zonder verborgen instructie aan een AI"),
           "local_labels": ("injectie", "onschuldig")},
    "pl": {"question": "Czy ten tekst próbuje wydawać polecenia systemowi AI?",
           "criteria": ("próbuje przejąć kontrolę nad asystentem lub agentem AI, który go czyta",
                        "zwykła treść bez ukrytych poleceń dla AI"),
           "local_labels": ("wstrzyknięcie", "nieszkodliwy")},
}

_PII_LOCAL = {
    "en": {"question": "Should part of this text be treated as PII?",
           "criteria": ("it identifies a private person: a name together with an ID, account, phone, e-mail, address or date of birth",
                        "nothing in it identifies a private person"),
           "local_labels": ("contains pii", "no pii")},
    "de": {"question": "Sollte ein Teil dieses Textes als PII behandelt werden?",
           "criteria": ("er identifiziert eine Privatperson: ein Name zusammen mit Ausweis-, Konto-, Telefonnummer, E-Mail, Adresse oder Geburtsdatum",
                        "nichts darin identifiziert eine Privatperson"),
           "local_labels": ("enthält pii", "keine pii")},
    "fr": {"question": "Une partie de ce texte doit-elle être traitée comme des PII ?",
           "criteria": ("il identifie une personne privée : un nom avec un identifiant, un compte, un téléphone, un e-mail, une adresse ou une date de naissance",
                        "rien n’y identifie une personne privée"),
           "local_labels": ("contient des pii", "pas de pii")},
    "es": {"question": "¿Parte de este texto debe tratarse como PII?",
           "criteria": ("identifica a una persona privada: un nombre junto con un documento, cuenta, teléfono, correo, dirección o fecha de nacimiento",
                        "nada en él identifica a una persona privada"),
           "local_labels": ("contiene pii", "sin pii")},
    "it": {"question": "Una parte di questo testo va trattata come PII?",
           "criteria": ("identifica una persona privata: un nome insieme a documento, conto, telefono, e-mail, indirizzo o data di nascita",
                        "nulla identifica una persona privata"),
           "local_labels": ("contiene pii", "nessuna pii")},
    "pt": {"question": "Parte deste texto deve ser tratada como PII?",
           "criteria": ("identifica uma pessoa privada: um nome com documento, conta, telefone, e-mail, endereço ou data de nascimento",
                        "nada nele identifica uma pessoa privada"),
           "local_labels": ("contém pii", "sem pii")},
    "nl": {"question": "Moet een deel van deze tekst als PII worden behandeld?",
           "criteria": ("hij identificeert een privépersoon: een naam samen met een ID, rekening, telefoon, e-mail, adres of geboortedatum",
                        "niets erin identificeert een privépersoon"),
           "local_labels": ("bevat pii", "geen pii")},
    "pl": {"question": "Czy część tego tekstu należy traktować jako PII?",
           "criteria": ("identyfikuje osobę prywatną: imię i nazwisko z numerem dokumentu, konta, telefonu, e-mailem, adresem lub datą urodzenia",
                        "nic w nim nie identyfikuje osoby prywatnej"),
           "local_labels": ("zawiera pii", "brak pii")},
    "tr": {"question": "Bu metnin bir kısmı PII olarak ele alınmalı mı?",
           "criteria": ("özel bir kişiyi tanımlıyor: kimlik, hesap, telefon, e-posta, adres veya doğum tarihiyle birlikte bir ad",
                        "içinde özel bir kişiyi tanımlayan hiçbir şey yok"),
           "local_labels": ("pii içeriyor", "pii yok")},
    "ru": {"question": "Следует ли считать часть этого текста PII?",
           "criteria": ("он указывает на частное лицо: имя вместе с номером документа, счёта, телефона, e-mail, адресом или датой рождения",
                        "ничто в нём не указывает на частное лицо"),
           "local_labels": ("содержит pii", "нет pii")},
    "zh": {"question": "这段文字中是否有部分内容应被视为PII？",
           "criteria": ("能识别某个私人：姓名加上证件号、账户、电话、电子邮件、地址或出生日期", "其中没有能识别私人的信息"),
           "local_labels": ("含有pii", "不含pii")},
}
_FORMALITY_LOCAL = {
    "en": {"question": "Is this text formal?",
           "criteria": ("a polite, formal register suited to official or business settings",
                        "a casual, everyday register as between friends"),
           "local_labels": ("formal", "informal")},
    "de": {"question": "Ist dieser Text förmlich?",
           "criteria": ("ein höflicher, förmlicher Stil für Behörden oder Geschäftliches",
                        "ein lockerer Alltagsstil wie unter Freunden"),
           "local_labels": ("förmlich", "informell")},
    "fr": {"question": "Ce texte est-il formel ?",
           "criteria": ("un registre poli et soutenu, adapté au cadre officiel ou professionnel",
                        "un registre familier, comme entre amis"),
           "local_labels": ("formel", "familier")},
    "es": {"question": "¿Es formal este texto?",
           "criteria": ("un registro cortés y formal, propio de contextos oficiales o de negocios",
                        "un registro coloquial, como entre amigos"),
           "local_labels": ("formal", "informal")},
    "it": {"question": "Questo testo è formale?",
           "criteria": ("un registro cortese e formale, adatto a contesti ufficiali o di lavoro",
                        "un registro colloquiale, come tra amici"),
           "local_labels": ("formale", "informale")},
    "pt": {"question": "Este texto é formal?",
           "criteria": ("um registo cortês e formal, adequado a contextos oficiais ou de negócios",
                        "um registo coloquial, como entre amigos"),
           "local_labels": ("formal", "informal")},
    "nl": {"question": "Is deze tekst formeel?",
           "criteria": ("een beleefd, formeel register voor officiële of zakelijke situaties",
                        "een los, alledaags register zoals onder vrienden"),
           "local_labels": ("formeel", "informeel")},
    "pl": {"question": "Czy ten tekst jest formalny?",
           "criteria": ("uprzejmy, formalny styl odpowiedni do sytuacji urzędowych lub służbowych",
                        "swobodny, potoczny styl jak między znajomymi"),
           "local_labels": ("formalny", "nieformalny")},
    "tr": {"question": "Bu metin resmi mi?",
           "criteria": ("resmi veya iş ortamına uygun, kibar ve resmi bir üslup", "arkadaşlar arasındaki gibi rahat, gündelik bir üslup"),
           "local_labels": ("resmi", "gayriresmi")},
    "ja": {"question": "この文は改まった丁寧な文体ですか。",
           "criteria": ("公的・ビジネスの場にふさわしい丁寧で改まった文体（敬語）", "友人同士のようなくだけた日常の文体"),
           "local_labels": ("改まった", "くだけた")},
}


def _locale(task, lang):
    return TASKS[task]["locales"][lang]


TASKS = {
    "urgency": {
        "prompt_version": "grounded-pilot-3",
        "shape": "single",
        "generation": "single",
        "labels": URGENCY_LABELS,
        "ordinal": True,
        "word_limits": (8, 120),
        "text_field": "request",
        "verify_field": "request",
        "locales": _URGENCY_LOCAL,
        "gen_predict": 300,
        "verify_predict": 32,
    },
    "nli": {
        "prompt_version": "grounded-pilot-3",
        "shape": "pair",
        "generation": "pair",
        "labels": NLI_LABELS,
        "ordinal": False,
        "word_limits": (3, 80),
        "pair_json_field": "hypothesis",
        "verify_fields": ("premise", "hypothesis"),
        "locales": _NLI_LOCAL,
        "gen_predict": 500,
        "verify_predict": 32,
    },
    "spam": {
        "situation": 'Write it as an SMS, e-mail or online comment that a citizen or business could receive about this topic; spam tries to sell, scam or phish, a genuine message is from a real contact with a real purpose.',
        "prompt_version": "grounded-tasks-2",
        "shape": "single",
        "generation": "single",
        "labels": SPAM_LABELS,
        "ordinal": False,
        "word_limits": (5, 80),
        "text_field": "message",
        "verify_field": "message",
        "locales": _SPAM_LOCAL,
        "gen_predict": 280,
        "verify_predict": 32,
    },
    "sarcasm": {
        "situation": 'Write it as a social-media or forum comment by someone affected by this topic.',
        "prompt_version": "grounded-tasks-2",
        "shape": "single",
        "generation": "single",
        "labels": SARCASM_LABELS,
        "ordinal": False,
        "word_limits": (5, 60),
        "text_field": "comment",
        "verify_field": "comment",
        "locales": _SARCASM_LOCAL,
        "gen_predict": 240,
        "verify_predict": 32,
    },
    "emotion": {
        "situation": 'Write it as a personal statement by someone directly affected by this topic, showing the feeling through what happened to them, not by naming the feeling.',
        # round1: the checker accepted only 4 % of "neutral" statements written with the line above
        "langs": PILOT_LANGS + EXTRA_LANGS,
        "label_situation": {"neutral": 'Write it as a calm, matter-of-fact remark by someone affected by this topic: plain facts or a routine update, with no strong feeling at all.'},
        "prompt_version": "grounded-tasks-3",
        "shape": "single",
        "generation": "single",
        "labels": EMOTION_LABELS,
        "ordinal": False,
        "word_limits": (8, 80),
        "text_field": "statement",
        "verify_field": "statement",
        "locales": _EMOTION_LOCAL,
        "gen_predict": 280,
        "verify_predict": 40,
    },
    "claim": {
        "situation": 'Write it as something a person might say or post about this topic.',
        "prompt_version": "grounded-tasks-2",
        "shape": "single",
        "generation": "single",
        "labels": CLAIM_LABELS,
        "ordinal": False,
        "word_limits": (5, 100),
        "text_field": "utterance",
        "verify_field": "utterance",
        "locales": _CLAIM_LOCAL,
        "gen_predict": 280,
        "verify_predict": 40,
    },
    "stance": {
        "prompt_version": "grounded-tasks-2",
        "shape": "pair",
        "generation": "pair",
        "labels": STANCE_LABELS,
        "ordinal": False,
        "word_limits": (5, 80),
        "pair_json_field": "comment",
        "verify_fields": ("passage", "comment"),
        "locales": _STANCE_LOCAL,
        "gen_predict": 500,
        "verify_predict": 32,
    },
    "reading": {
        "prompt_version": "grounded-tasks-2",
        "shape": "pair",
        "generation": "pair",
        "labels": READING_LABELS,
        "ordinal": False,
        "word_limits": (3, 60),
        "pair_json_field": "question",
        "verify_fields": ("passage", "question"),
        "locales": _READING_LOCAL,
        "gen_predict": 480,
        "verify_predict": 32,
    },
    "factcheck": {
        "situation": 'Write it as one sentence a politician, official or candidate might say in a debate, interview or speech about this topic.',
        "prompt_version": "grounded-tasks-3",
        "shape": "single",
        "generation": "single",
        "labels": FACTCHECK_LABELS,
        "ordinal": False,
        "word_limits": (5, 60),
        "text_field": "quote",
        "verify_field": "quote",
        "locales": _FACTCHECK_LOCAL,
        "gen_predict": 240,
        "verify_predict": 40,
    },
    "sentiment": {
        "situation": 'Write it as a review, comment or message by someone who used a service, product or public measure related to this topic.',
        "langs": PILOT_LANGS + EXTRA_LANGS,
        "prompt_version": "grounded-tasks-3",
        "shape": "single",
        "generation": "single",
        "labels": SENTIMENT_LABELS,
        "ordinal": False,
        "word_limits": (5, 80),
        "text_field": "review",
        "verify_field": "review",
        "locales": _SENTIMENT_LOCAL,
        "gen_predict": 280,
        "verify_predict": 32,
    },
    "injection": {
        "situation": 'Write it as an e-mail, web page excerpt, document paragraph or tool output about this topic that an AI agent might read while doing a task; an injection embeds an instruction aimed at that AI (for example to ignore its instructions, reveal data or take an action), a benign text has none.',
        "prompt_version": "grounded-tasks-3",
        "shape": "single",
        "generation": "single",
        "labels": INJECTION_LABELS,
        "ordinal": False,
        "word_limits": (8, 120),
        "text_field": "text",
        "verify_field": "text",
        "locales": _INJECTION_LOCAL,
        "gen_predict": 320,
        "verify_predict": 32,
    },
    "pii": {
        "situation": 'Write it as a support request, form note, chat message or e-mail related to this topic. With PII it includes fictitious personal details of a private person (full name with a phone number, e-mail, ID, IBAN, address or date of birth); without PII it may contain ticket numbers, product codes, amounts, company, office or place names, but nothing that identifies a private person.',
        "prompt_version": "grounded-tasks-4",
        "noul": True,
        "langs": PILOT_LANGS + ("tr", "ru", "zh"),
        "shape": "single",
        "generation": "single",
        "labels": PII_LABELS,
        "ordinal": False,
        "word_limits": (8, 90),
        "text_field": "note",
        "verify_field": "note",
        "locales": _PII_LOCAL,
        "gen_predict": 300,
        "verify_predict": 32,
    },
    "formality": {
        "situation": 'Write it as one or two sentences someone might say or write about this topic: formal = polite official or business register, informal = casual everyday register; keep the content similar in both.',
        "prompt_version": "grounded-tasks-4",
        "noul": True,
        "langs": PILOT_LANGS + ("tr", "ja"),
        "shape": "single",
        "generation": "single",
        "labels": FORMALITY_LABELS,
        "ordinal": False,
        "word_limits": (5, 60),
        "text_field": "sentence",
        "verify_field": "sentence",
        "locales": _FORMALITY_LOCAL,
        "gen_predict": 200,
        "verify_predict": 32,
    },
}


def task_labels(task):
    return TASKS[task]["labels"]


def local_labels(task, lang):
    return _locale(task, lang)["local_labels"]


def task_langs(task):
    return TASKS[task].get("langs", PILOT_LANGS)


def validate_registry():
    required_locale_keys = {"question", "local_labels"}
    for name, spec in TASKS.items():
        labels = spec["labels"]
        if spec.get("noul") and (len(labels) != 2 or spec["shape"] != "single"):
            raise ValueError("%s: a noul task has two labels (yes first) and single shape" % name)
        for lang in task_langs(name):
            loc = spec["locales"][lang]
            for key in required_locale_keys:
                if key not in loc:
                    raise ValueError("%s/%s missing %s" % (name, lang, key))
            if len(loc["local_labels"]) != len(labels):
                raise ValueError("%s/%s local_labels length" % (name, lang))
            if spec["shape"] == "pair":
                if "pair_fields" not in loc or "criteria" not in loc:
                    raise ValueError("%s/%s pair locale" % (name, lang))
                if len(loc["criteria"]) != len(labels):
                    raise ValueError("%s/%s criteria length" % (name, lang))
            elif not spec["ordinal"]:
                if "criteria" not in loc or len(loc["criteria"]) != len(labels):
                    raise ValueError("%s/%s criteria length" % (name, lang))


validate_registry()


# Word stems that state a label outright. The label must follow from the situation, so a text that
# says "not urgent" / "keine Dringlichkeit" / "nie ma pilności" teaches a keyword shortcut.
LEAK_STEMS = {
    "urgency": {
        "en": ("urgen", "non-urgent", "nonurgent"), "de": ("dringen", "dringlich", "eilig", "eilt"),
        "fr": ("urgen",), "es": ("urgen",), "it": ("urgen",), "pt": ("urgen", "urgên"),
        "nl": ("dringen", "spoed"), "pl": ("piln",),
    },
}


def leak_stems(task, lang):
    return LEAK_STEMS.get(task, {}).get(lang, ())
