#pragma once

#include <bit>
#include <cstddef>
#include <atomic>
#include <cstdint>
#include <chrono>
#include <cmath>
#include <string>
#include <vector>

struct ggml_tensor;

namespace statim {

// Coefficients are generated by tools/kernels/fit_erf.py.  The two polynomial
// regions deliberately avoid division; interval choices compile to vector blends.
inline float erf_approx(float x) {
    const uint32_t bits = std::bit_cast<uint32_t>(x);
    const uint32_t abits = bits & 0x7fffffffu;
    const float ax = std::bit_cast<float>(abits);
    const float sx = ax < 1.0f ? ax : 1.0f;
    const float st = 2.0f * sx * sx - 1.0f;
    const float sp = 9.654687643e-01f + st * (-1.405360848e-01f + st *
        (1.985249668e-02f + st * (-2.285485622e-03f + st *
        (2.175127011e-04f + st * (-1.753686593e-05f + st *
        (1.231088277e-06f + st * -7.554783821e-08f))))));
    const float small = ax * sp;
    const float tx = ax < 1.0f ? 1.0f : (ax > 3.92f ? 3.92f : ax);
    const float tt = tx * 0.684931506849315f - 1.684931506849315f;
    const float tail = 9.994966388e-01f + tt * (3.878132673e-03f + tt *
        (-1.392897964e-02f + tt * (3.059911355e-02f + tt *
        (-4.504733533e-02f + tt * (4.511431605e-02f + tt *
        (-2.844717726e-02f + tt * (6.468094885e-03f + tt *
        (7.346181665e-03f + tt * (-8.982375264e-03f + tt *
        (3.339305753e-03f + tt * (1.545698149e-03f + tt *
        (-1.627641846e-03f + tt * (2.663230589e-05f + tt * 2.193804539e-04f)))))))))))));
    const float magnitude = ax < 1.0f ? small : (ax < 3.92f ? tail : 1.0f);
    const float finite = std::bit_cast<float>(std::bit_cast<uint32_t>(magnitude) |
                                              (bits & 0x80000000u));
    return abits > 0x7f800000u ? x + x : finite;
}

struct SgemmAbort {
    std::chrono::steady_clock::time_point deadline = std::chrono::steady_clock::time_point::max();
    const std::atomic<bool>* cancelled = nullptr;
    bool requested() const {
        return (cancelled && cancelled->load(std::memory_order_relaxed)) ||
               (deadline != std::chrono::steady_clock::time_point::max() &&
                std::chrono::steady_clock::now() >= deadline);
    }
};
void geglu_rows(float* dst, const float* src, long rows, long ff, long row_begin, long row_end);

// Y[N, M] = X[N, K] * W[M, K]^T.  ggml stores the corresponding tensors as
// [M, N], [K, N], and [K, M], so dimension zero is the contiguous dimension.
// Each caller handles one of nth disjoint groups of 16-column output tiles.
bool packed_sgemm_available();
bool packed_sgemm_enabled();
std::vector<std::string> matrix_cpu_features();
size_t packed_sgemm_workspace_floats(int64_t M, int64_t N, int64_t K);
void packed_sgemm_pack(float* workspace, const float* x, const float* w,
                       int64_t M, int64_t N, int64_t K, int ith, int nth);
// ggml custom-op body for dst = W·x with src = {W [K, M], x [K, N...]}: every thread
// packs its share of x, waits at the barrier, then computes its output tiles. userdata is a
// SgemmOpSync owned by the graph; it may be reused for any number of evaluations.
struct SgemmOpSync {
    std::atomic<int> arrived{0};
    std::atomic<uint32_t> generation{0};
    const SgemmAbort* abort = nullptr;
    // Packed-activation workspace. The graph runs one node at a time, so every projection of a
    // graph shares one buffer; a graph tensor would stay allocated for the whole graph instead.
    float* workspace = nullptr;
    size_t workspace_floats = 0;  // needed by this node; the shared buffer is at least this large
};
void sgemm_custom_op(ggml_tensor* dst, int ith, int nth, void* userdata);

void packed_sgemm_compute(float* y, const float* workspace, const float* w,
                          int64_t M, int64_t N, int64_t K, int ith, int nth);
}
